# Generated by Django 6.0.4 on 2026-08-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_servicerate_project_category_project_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='YOUR NAME', max_length=100)),
                ('label', models.CharField(default='// EDITOR & PHOTOGRAPHER', max_length=100)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_x_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Photographer Profile',
                'verbose_name_plural': 'Photographer Profile',
            },
        ),
    ]
