# Generated by Django 6.0.4 on 2026-08-14 18:04

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_photographerprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Optional. Upload on cloudinary.com, then paste the image URL here.'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Optional. Upload on cloudinary.com, then paste the image URL here.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='projects/'),
        ),
    ]
